# Generated by Django 3.0.8 on 2020-07-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destino_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='estado',
            new_name='state',
        ),
    ]
